name: Build and deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [ build ]

jobs:

  run:

    runs-on: Ubuntu-20.04

    steps:

    - name: Wait for other builds to finish
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Checkout incontext
      uses: actions/checkout@v2
      with:
        repository: jbmorley/incontext
        path: incontext
        ref: main
        token: ${{ secrets.TOKEN }}

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        path: site

    - name: Build the site
      run: |
        python3 incontext/incontext --site site build
        rm -r gh-pages/*
        cp -R site/build/files/* gh-pages

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        path: gh-pages
        ref: gh-pages

    - name: Copy build output
      run: |
        rm -r gh-pages/*
        cp -R site/build/files/* gh-pages

    - name: Commit the site to gh-pages
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update auto-generated documentation
        repository: gh-pages
        branch: gh-pages
