name: Update documentation

on:
  schedule:
    - cron: '0 */6 * * *'
  repository_dispatch:
    types: [ update-documentation ]
    
jobs:

  run:
      
    runs-on: Ubuntu-20.04
    
    steps:

    - name: Wait for other builds to finish
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        path: site
        ref: main
        
    - name: Checkout site repository
      uses: actions/checkout@v2
      with:
        repository: jbmorley/incontext
        ref: main
        path: incontext
        token: ${{ secrets.TOKEN }}
        
    - name: Build documentation
      run: |
        mkdir -p site/content/docs
        python3 -u incontext/incontext build-documentation site/content/docs

    - name: Commit documentation
      uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit
      with:
        commit_message: Update auto-generated documentation
        repository: site
        branch: main
        
    - name: Trigger rebuild
      if: steps.auto-commit.outputs.changes_detected == 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TOKEN }}
        event-type: build
